# Generated by Django 2.1.9 on 2019-06-15 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_min',
            new_name='time_minutes',
        ),
    ]
